#### Without Function 

In [39]:
w1, w2, w3=0.3, 0.2, 0.5

region=['kanto', 'johto', 'hoenn', 'sinnoh', 'unova']
temp=[73, 91, 87, 102, 69]
rainfall=[67, 88, 134, 43, 96]
humidity=[43, 64, 58, 37,70]

for i in range(0,5,1):
    region[i]=temp[i]*w1+rainfall[i]*w2+humidity[i]*w3
    print(region[i])

56.8
76.9
81.9
57.699999999999996
74.9


In [40]:
w1, w2, w3=0.3, 0.2, 0.5

In [41]:
region=['kanto', 'johto', 'hoenn', 'sinnoh', 'unova']
temp=[73, 91, 87, 102, 69]
rainfall=[67, 88, 134, 43, 96]
humidity=[43, 64, 58, 37,70]

In [42]:
for i in range(0,5,1):
    region[i]=temp[i]*w1+rainfall[i]*w2+humidity[i]*w3
    print(region[i])

56.8
76.9
81.9
57.699999999999996
74.9


#### or

#### With Function 

In [43]:
w1, w2, w3=0.3, 0.2, 0.5

In [44]:
weights=[w1, w2, w3]

In [45]:
kanto=[73, 67, 43]
johto=[91, 88, 64]
sinnoh=[87, 134, 58]
hoenn=[102, 43, 37]
unova=[69, 96, 70]

In [46]:
zip(kanto,weights)

In [47]:
zip(kanto,weights)

In [48]:
def crop_yield(region, weights):
    result=0
    for x, w in zip(region,weights):
        result+=x*w
        return result

In [49]:
crop_yield(kanto, weights)

21.9

In [50]:
crop_yield(johto, weights)

27.3

In [51]:
crop_yield(sinnoh, weights)

26.099999999999998

In [52]:
crop_yield(hoenn, weights)

30.599999999999998

In [79]:
crop_yield(unova, weights)

20.7

#### Testing with functions 

In [54]:
w1, w2, w3=0.3, 0.2, 0.5

In [55]:
region=['kanto', 'johto', 'hoenn', 'sinnoh', 'unova']
temp=[73, 91, 87, 102, 69]
rainfall=[67, 88, 134, 43, 96]
humidity=[43, 64, 58, 37,70]

In [56]:
def test(a,b,c,t,r,h): 
    return (t*a+r*b+h*c)
    

In [57]:
for i in range(0,5,1):
    reg=test(w1, w2, w3, temp[i], rainfall[i], humidity[i])
    print(f"{region[i]}= ", reg)

kanto=  56.8
johto=  76.9
hoenn=  81.9
sinnoh=  57.699999999999996
unova=  74.9


# Numpy  

In [58]:
kanto=[73, 67, 43]
johto=[91, 88, 64]
sinnoh=[87, 134, 58]
hoenn=[102, 43, 37]
unova=[69, 96, 70]

In [59]:
w1, w2, w3=0.3, 0.2, 0.5

In [60]:
import numpy as np

In [61]:
kanto

[73, 67, 43]

### We can now use the np.array function to create Numpy arrays 

In [62]:
kanto=np.array([73, 67, 43])

In [63]:
kanto

array([73, 67, 43])

In [64]:
type(kanto)

numpy.ndarray

In [65]:
#Ek square bracket hai matlab one dimensio hai par 3 column kyuki 3 elements hai

In [66]:
weights=np.array([w1, w2, w3])

In [67]:
weights

array([0.3, 0.2, 0.5])

In [68]:
type(johto)

list

In [69]:
type(weights)

numpy.ndarray

### Just like lists, Numpy arrays support the indexing notation[] 

In [70]:
weights[0]

0.3

In [71]:
kanto[2]

43

# Operations on Numpy arrays

In [72]:
#We can now compute the dot product of the two vectors using np.dot function

In [73]:
np.dot(kanto, weights)

56.8

In [74]:
#Python lists
arr1= list(range(1000000))
arr2= list(range(1000000, 2000000))

#Numpy arrays
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

In [75]:
arr1_np

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [76]:
arr2_np

array([1000000, 1000001, 1000002, ..., 1999997, 1999998, 1999999])

In [77]:
%%time 
result=0
for x1, x2 in zip(arr1,arr2):
    result+=x1*x2
result

CPU times: total: 266 ms
Wall time: 382 ms


833332333333500000

In [78]:
%%time 
result1=np.dot(arr1_np, arr2_np)
result1

CPU times: total: 0 ns
Wall time: 1.45 ms


-1942957984

# MULTI-DIMENSIONAL NUMPY ARRAYS


In [3]:
import numpy as np      
      #3,3,2,2

In [11]:
arr3= np.array([[[1,2],[2,3],
                 [4,5],[3,4],
                 [4,4],[6,7]]],
                
                [[[1,2],[2,3],
                 [4,5],[3,4],
                 [4,4],[6,7]],
                
                 [[[1,2],[2,3],
                 [4,5],[3,4],
                 [4,4],[6,7]])
               

In [12]:
arr3.shape

(3, 6, 2)

In [16]:
arr3 = np.array([[[1,2,3],[3,4,5]],
                 [[1,2,3],[3,4,5]]
                 
    
])

In [14]:
arr3.shape

(2, 2, 3)

In [17]:
arr3 = np.array([[[3]],
                 [[4]],
                 [[5]].
    
])

SyntaxError: invalid syntax (864112422.py, line 5)

# WORKING WITH CSV DATA FILES